server:
  http:
    addr: 0.0.0.0:8000
    timeout: 10s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: binance_data:sFnJyzzMixsTw2m8@tcp(18.179.77.137:3306)/binance_data?parseTime=true
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 1s
    write_timeout: 1s
